### ISSUE TITLE
Can't sign up your account from sitechef website.

### ISSUE THREAD

**Issue by lephuhai** [sitechef/sitechef-cli#2]
I following the [documentation](http://themedocs.sitechef.co.uk/installation/) and signup new account with google but throw `ACCOUNT NOT REGISTERED`. So, i can't generator api key for init your project using `sitechef-cli`.

I hope get your answer. Thanks!

**Comment by campbellwmorgan** [comment]
hi @Vietworm thanks for the interest in our project. Sitechef helps developers make and manage great hotel and restaurant websites. If you'd like to have a play with our system, drop us an email at dev@sitechef.co.uk and let us know what sort of websites you'll be making and we'll give you access.

Thanks
